_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
bias:
    value: false
block_size:
    value: 256
dropout:
    value: 0.2
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
